### ISSUE TITLE
Choosing preferences crashes Rhythmbox

### ISSUE THREAD

**Issue by scisus** [BramBonne/LastfmPlaycount#6] opened 2012-02-23 21:14 UTC
When I click the 'Preferences' button in plugins for LastfmPlaycount, Rhythmbox crashes.

sus@seventysix:~$ rhythmbox -D lastfmplaycount

/usr/lib/python2.7/dist-packages/gobject/constants.py:24: Warning: g_boxed_type_register_static: assertion `g_type_from_name (name) == 0' failed
  import gobject._gobject
(13:01:37) [0x1b380c0] [Config._parse_username] /usr/lib/rhythmbox/plugins/lastfmplaycount/lastfmplaycountconfig.py:267: Parsed Last.fm username: sarcozona
(13:01:37) [0x1b380c0] [Config.set_run_update_all] /usr/lib/rhythmbox/plugins/lastfmplaycount/lastfmplaycountconfig.py:231: Run_update False
(13:01:37) [0x1b380c0] [LastfmPlaycountPlugin.do_activate] /usr/lib/rhythmbox/plugins/lastfmplaycount/lastfmplaycount.py:109: Activation finished
(rhythmbox:2324): Rhythmbox-DEBUG: Received SaveYourself(SmSaveLocal, !Shutdown, SmInteractStyleNone, !Fast) in state idle
(rhythmbox:2324): Rhythmbox-DEBUG: Setting initial properties
(rhythmbox:2324): Rhythmbox-DEBUG: Sending SaveYourselfDone(True) for initial SaveYourself
(rhythmbox:2324): Rhythmbox-DEBUG: Received SaveComplete message in state save-yourself-done
(13:02:09) [0x2f2b9b0] [LastfmPlaycountPlugin.update_entry] /usr/lib/rhythmbox/plugins/lastfmplaycount/lastfmplaycount.py:249: Playcount for \'tUnE-yArDs' - \'Doorstep' remained the same. Not updating
(13:02:28) [0x2b44aa0] [LastfmPlaycountPlugin.update_entry] /usr/lib/rhythmbox/plugins/lastfmplaycount/lastfmplaycount.py:244: Setting playcount of "'listenlisten' - 'Watchman'" to 2
(13:03:11) [0x1b380c0] [Config._parse_username] /usr/lib/rhythmbox/plugins/lastfmplaycount/lastfmplaycountconfig.py:267: Parsed Last.fm username: sarcozona
(13:03:11) [0x1b380c0] [Config.set_run_update_all] /usr/lib/rhythmbox/plugins/lastfmplaycount/lastfmplaycountconfig.py:231: Run_update False
(13:03:11) [0x1b380c0] [Config.do_create_configure_widget] /usr/lib/rhythmbox/plugins/lastfmplaycount/lastfmplaycountconfig.py:90: Creating configuration dialog
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/lastfmplaycount/lastfmplaycountconfig.py", line 49, in do_create_configure_widget
    builder.add_from_file(rb.find_plugin_file(self, "lastfmplaycount-prefs.ui"))
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
TypeError: Argument 1 does not allow None as a value
Segmentation fault

**Comment by BramBonne** [comment] 2015-09-13 09:27
It seems that the problem is that rhythmbox can not find the 'lastfmplaycount-prefs.ui' file. Could you check that you (or the install script) copied that file correctly to the plugins directory?

**Comment by BramBonne** [comment] 2015-09-23 14:58
Closing this as there is insufficient information to reproduce the issue. Please feel free to reopen this if you think this is a legitimate issue.

**Closed by BramBonne** 2015-09-23 14:58 UTC
